[package]
name = "curds_core_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.75", features = ["parsing", "extra-traits", "full"] }
quote = "1.0.9"
proc-macro-crate = "3.1.0"
rand = "0.8.4"
proc-macro2 = "1.0.28"
regex = "1.10.2"