[package]
name = "curds_core"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.19"
regex = "1.10.5"
curds_core_abstraction = { path = "../curds_core_abstraction" }
curds_core_macro = { path = "../curds_core_macro" }